### ISSUE TITLE
Add RSS feed

### ISSUE THREAD

**Issue by cmeeren** [TysonMN/tyson-williams-blog#23]
I would like to follow your blog for updates. I don't want to remember to manually come by every now and then. My preferred solution is to use an RSS reader such as Feedly, but it doesn't seem that your blog has any feeds. Would this be possible to add?

**Comment by TysonMN** [comment]
Yes, definitely possible, and [this is how to do it](https://connect-platform.github.io/coding-blog-plugin/rss).  I also like RSS, use Feedly, and it has been on my list of improvements to add an RSS link.  Because you asked about it, I will make this the top priority item and complete it soon :)

**Comment by TysonMN** [comment]
I added support for RSS (and Atom and JSON).  I only know of one "bug" (see https://github.com/CONNECT-platform/coding-blog-plugin/issues/29).  Please let me know if you notice anything else wrong.

**Comment by cmeeren** [comment]
Great, thanks!
